version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    networks:
      local:
    environment:
      DB_ADDRESS: "mongodb://mongo:27017/cheil"

  mongo:
    image: mongo
    volumes:
      - db:/data/db
    networks:
      local:
        aliases:
          - mongo

  mongo-restore:
    image: mongo
    volumes:
      - ./mongodump:/dump
      - db:/data/db
    command:
      /bin/sh -c "mongorestore --uri 'mongodb://mongo:27017' /dump && echo 'MongoDB Restore Complete'"
    depends_on:
      - mongo
    networks:
      local:

networks:
  local:

volumes:
  db:
