version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    networks:
      local:
    environment:
      DB_ADDRESS: "mongodb://mongo:27017/cheil"
  mongo:
    image: mongo
    volumes:
      - db:/data/db
    networks:
      local:
        aliases:
          - mongo


networks:
  local:

volumes:
  db: